# Generated by Django 5.1.3 on 2024-11-20 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0004_alter_course_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='slug',
        ),
    ]
