# Generated by Django 5.1.3 on 2024-11-20 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0005_remove_course_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Set to true when the course is ready for students'),
        ),
    ]
