# Generated by Django 5.1.3 on 2024-11-20 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0006_alter_course_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='is_free',
            field=models.BooleanField(default=True),
        ),
    ]
