# Generated by Django 5.1.3 on 2024-11-26 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0009_alter_lesson_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
