# Generated by Django 5.1.3 on 2024-11-26 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0010_alter_lesson_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
