# Generated by Django 5.1.3 on 2024-12-02 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0013_alter_assignment_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='grade',
            field=models.FloatField(blank=True, help_text='Grade for the student', null=True),
        ),
    ]
