# Generated by Django 5.1.3 on 2024-12-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0014_user_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='grade',
            field=models.FloatField(blank=True, default=0, help_text='Grade for the student', null=True),
        ),
    ]
