# Generated by Django 5.1.3 on 2024-12-03 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0015_alter_user_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='courses_purchased',
            field=models.ManyToManyField(blank=True, related_name='purchased_courses', to='LMS.course'),
        ),
    ]
