# Generated by Django 5.1.3 on 2024-12-06 10:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0018_lesson_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='enrolled_students',
            field=models.ManyToManyField(blank=True, related_name='enrolled_students', to=settings.AUTH_USER_MODEL),
        ),
    ]
