# Generated by Django 5.1.3 on 2024-12-17 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0020_userprogress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='difficulty_level',
        ),
    ]
