# Generated by Django 5.1.3 on 2024-12-17 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0021_remove_course_difficulty_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='course_media/')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='media_file',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='video_url',
        ),
        migrations.AddField(
            model_name='lesson',
            name='media_file',
            field=models.ManyToManyField(blank=True, to='LMS.mediafile'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_url',
            field=models.ManyToManyField(blank=True, to='LMS.video'),
        ),
    ]
