# Generated by Django 5.1.3 on 2024-12-28 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LMS", "0001_squashed_0032_remove_assignmentsubmission_question_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignmentsubmission",
            name="student_answers",
            field=models.JSONField(default=dict),
        ),
        migrations.DeleteModel(
            name="UserAnswer",
        ),
    ]
