# Generated by Django 5.1.3 on 2025-01-01 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LMS", "0034_alter_assignmentsubmission_is_correct"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="socket_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
