# Generated by Django 5.1.2 on 2025-02-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS', '0036_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_passed',
            field=models.BooleanField(default=False),
        ),
    ]
